config/routes.rb
Ncp::Application.routes.draw do

  resources :activities


  mount Ckeditor::Engine => '/ckeditor'



  resources :projects

  match '/about' => 'static_pages#about'
  match '/contacts' => 'static_pages#contacts'
  match '/cooperation' => 'static_pages#cooperation'
  match '/vacancies' => 'static_pages#vacancies'
  
  root :to => 'static_pages#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :text, :title
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/system/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/system/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/system/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/system/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :text, :title
end

app/controllers/activities_controller.rb
class ActivitiesController < InheritedResources::Base
  def index
    @activities = Activity.all
    @activity = Activity.first

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activies }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @activities = Activity.all
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @project = Project.first

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @projects = Project.all
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def contacts
  end

  def about
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
# coding: utf-8

module ApplicationHelper
  
  def title
     base_title = "Научный Центр Прикладной Электродинамики"
     if @title.nil?
       base_title
     else
       "#{base_title} | #{@title}"
     end
   end
   
   def nav_link(link_text, link_path)
     class_name = current_page?(link_path) ? 'active' : ''
     link_to link_text, link_path, :class => class_name
   end
   
   def controller?(*controller)
      controller.include?(params[:controller])
    end

    def action?(*action)
      action.include?(params[:action])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/activities/_activity.html.erb
<div class="proj-content">
	
	<%= @activity.text.html_safe %>
	
</div>

app/views/activities/_proj-list.html.erb
<div class="proj-list">
	<ul id="project-list">
		<% @activities.each do |activity| %>
		<li><%= link_to activity_path(activity) do %>
			<div class="<%= if activity.id == @activity.id then "btn get-content btn-primary" else "btn get-content" end %>" style="margin-bottom: 3px; width: 140px"><%= activity.title %></div>
		<% end %></li>
		<% end %>
	</ul>
</div>

app/views/activities/index.html.erb
<% @title = "Направления деятельности" %>

<div class="main_block">
	
	<%= render 'proj-list' %>
	
	<%= render @activity %>
	
	
</div>

app/views/activities/show.html.erb
<% @title = @activity.title %>

<div class="main_block">
	
	<%= render 'proj-list' %>
	
	<%= render @activity %>
	
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
<div id="wrapper">
<%= render 'shared/header' %>
<%= yield %>
<%= render 'shared/footer' %>
</div>
</body>
</html>

app/views/projects/_proj-list.html.erb
<div class="proj-list">
	<ul id="project-list">
		<% @projects.each do |project| %>
		<li><%= link_to project_path(project) do %>
			<div class="<%= if project.id == @project.id then "btn get-content btn-primary" else "btn get-content" end %>" style="margin-bottom: 3px; width: 140px"><%= project.title %></div>
		<% end %></li>
		<% end %>
	</ul>
</div>

app/views/projects/_project.html.erb
<div class="proj-content">
	
	<%= @project.text.html_safe %>
	
</div>

app/views/projects/index.html.erb
<% @title = "Проекты" %>

<div class="main_block">
	
	<%= render 'proj-list' %>
	
	<%= render @project %>
	
	
</div>

app/views/projects/show.html.erb
<% @title = @project.title %>

<div class="main_block">
	
	<%= render 'proj-list' %>
	
	<%= render @project %>
	
	
</div>

app/views/shared/_footer.html.erb
<div class="clear"></div>
<div class="foot_border"></div>
<div class="footer">
	<div class="foot-additional-menu to-mobile" style="position: absolute; left: 30px; top: 15px; width: 200px; height: 30px;">
		
		
	</div>
	<div class="foot-additional-menu to-projects" style="margin-left: 30px;position: absolute; left: 100px; top: 15px; width: 150px; height: 30px;">
		
	</div>
	<!--
	<div class="foot-additional-menu to-map" style="margin-left: 30px;position: absolute; left: 175px; top: 15px; width: 150px; height: 30px;">
		<p><a href="/ru/sitemap/" class="foot-link" style="font-size: 14px;">Карта</a></p>
	</div>
	-->
	<div class="foot-additional-menu to-news" style="margin-left: 30px;position: absolute; left: 175px; top: 15px; width: 150px; height: 30px;">
		
	</div>
	<div class="foot-right" style="position: absolute; right: 2px; top: 15px; text-align: right;">
	<p style="line-height: 180%">
		Научный центр прикладной электродинамики<br>
		190103, Российская Федерация, Санкт-Петербург<br> Рижский пр. 26, лит. А пом. 10Н, ком. 22<br>
		Тел.: +7 (812) 324-25-87<br>
		email: <a class="main_mail" href="mailto:office@scaegroup.com">office@scaegroup.com</a>
	</p>
	</div>
	<div class="foot-additional-menu to-mobile" style="position: absolute; left: 30px; bottom: -20px; width: 200px; height: 30px;">
		<p>&copy; 2005-2013 ООО "НЦПЭ"</p>
	</div>		
</div>

app/views/shared/_header.html.erb
<div class="header">

		<div class="header_contacts">
			<div class="header-tel">(812) 324 25 87</div>
			<div class="header-email"><a href="mailto:office@scaegroup.com">office@scaegroup.com</a></div>
		</div>
		
</div>
<div class="main_menu">
	<ul>	
		
		<li id="m_news"><%= nav_link "Главная", root_path %></li>
		<li id="m_about"><%= nav_link "О нас", about_path %></li>
		<li id="m_activities"><%= link_to "Направления деятельности", activities_path, :class => ('active' if controller?("activities")) %></li>
		<li id="m_projects"><%= link_to "Проекты", projects_path, :class => ('active' if controller?("projects")) %></li>
		<li id="m_cooperation"><%= nav_link "Сотрудничество", cooperation_path %></li>
		<li id="m_jobs"><%= nav_link "Вакансии", vacancies_path %></li>
		<li id="m_contacts"><%= nav_link "Контакты", contacts_path %></li>
	</ul>
</div>
<br>

app/views/static_pages/about.html.erb
<% @title = 'О нас' %>

<div class="main_block">
	<div class="infoblock">
		<p style="text-indent: 20px;">
		Научный центр прикладной электродинамики - общество с ограниченной ответственностью, созданное в 2002 году. В своей практической деятельности мы решаем задачи высшего уровня сложности в области электродинамики, антенной техники, электромагнитной совместимости, а также распространения и рассеяния радиоволн на объектах сложной формы. Вместе с тем предприятие имеет базу для решения прикладных задач по разработке, проектированию, изготовлению опытных образцов, настройке и регулировке антенн любых типов и любого функционального назначения - от антенн мобильных телефонов до радиотелескопов, включая адаптивные и сверхширокополосные антенны.
		Партнерами НЦ ПЭ являются такие предприятия как ФГУП КБ "Арсенал", ФГУП ЦНИИ "Электроприбор", ОАО "Завод "Энергия", ОАО РИРВ, Государственный НИИ прикладных проблем ФСТЭК России, НИИ "Вектор" и др.</p><br><p style="text-indent: 20px;">
		ООО "Научный центр прикладной электродинамики" участвует в научных программах под эгидой Российской Академии Наук (Санкт-Петербургский Научный Центр Российской Академии Наук, Астро-Космический Центр при РАН, Физический институт им. П. Н. Лебедева РАН), проводит научные исследования по совершенствованию экспериментальной базы при разработке новых образцов антенной техники, участвует в разработке перспективных и конкурентоспособных антенн для радиоэлектронных средств различного назначения.
		</p><br>
		<p><strong>Разработка:</strong></p>

<ul style="margin-left: 40px;">
	<li>одиночных антенн, антенных решеток, антенн пеленгаторов, адаптивных антенных решеток</li>
	<li>аппаратно-программных комплексов</li>
	<li>программных продуктов в области электродинамики</li>
</ul>

<p><strong>Расчет</strong></p>

<ul style="margin-left: 40px;">
	<li>полей рассеяния на реальных объектах сложной формы</li>
	<li>ЭМС в пределах РЭС, отсека, объекта в целом</li>
	<li>влияния подстилающей поверхности на параметры и характеристики антенн и радиоэлектронных устройств в целом</li>
</ul>

<p><strong>Изготовление</strong></p>

<ul style="margin-left: 40px;">
	<li>одиночных антенн, антенных решеток, антенн пеленгаторов, адаптивных антенных решеток</li>
	<li>устройств обработки сигналов</li>
	<li>аппаратно-программных комплексов</li>
</ul>

<p><strong>Измерение</strong></p>

<ul style="margin-left: 40px;">
	<li>параметров и характеристик антенн</li>
</ul>
		<br>
</div>
</div>

app/views/static_pages/contacts.html.erb
<% @title = "Контакты" %>
<div class="main_block">
	<ul class="contacts" style="width: 1000px;">
		<li id="address" style="margin-left: 30px">
			<p>
				<b>Телефон/факс:</b><br>
				+7 (812) 3242587<br>
				+7 (812) 3242506<br>
				+7 (812) 3258329<br>
				<br>
				<b>E-mail:</b>
				<a href="mailto:office@scaegroup.com">office@scaegroup.com</a><br><br>
				<b>Адрес:</b><br>
				190103<br>
				Российския Федерация<br>
				Санкт-Петербург<br>
				Рижский проспект, дом 26<br>
				лит. А пом. 10Н, ком. 22<br>
			</p><br>
			<a href="http://maps.yandex.ru/?um=YBZAi0czaBWvpeJ1HM6FC2h9Cy0gYm51&amp;l=map" target="_blank"><div class="btn" style="width:100px; margin-bottom: 5px;">Яндекс.Карты</div></a>
			<a href="http://goo.gl/maps/xXr1X" target="_blank"><div class="btn" style="width:100px;">Google Maps</div></a>
		</li>
		<li id="map">
			<div id="map_canvas">
				<iframe width="670" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.ru/maps?sll=59.913582999999996,30.28977699999999&amp;sspn=0.003302249659602066,0.013732554430715074&amp;t=m&amp;q=%D0%A0%D0%B8%D0%B6%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80%D0%BE%D1%81%D0%BF%D0%B5%D0%BA%D1%82,+%D0%B4%D0%BE%D0%BC+26+%D0%BB%D0%B8%D1%82.+%D0%90&amp;ie=UTF8&amp;hq=&amp;hnear=%D0%A0%D0%B8%D0%B6%D1%81%D0%BA%D0%B8%D0%B9+%D0%BF%D1%80%D0%BE%D1%81%D0%BF.,+26,+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3,+%D0%B3%D0%BE%D1%80%D0%BE%D0%B4+%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3&amp;ll=59.915257,30.291324&amp;spn=0.008605,0.028796&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe>
			</div>
		</li>
	</ul>
</div>

app/views/static_pages/cooperation.html.erb
<% @title = "Сотрудничество" %> 


<div class="main_block">
	<!--<img src="/static/scae/base/img/under_construct.png" style="padding-left: 150px;"/>-->
	<img src="/assets/underconstruct.jpg" style="padding-left: 200px;"/>
</div>

app/views/static_pages/index.html.erb
<div class="main_block" style="min-height: 398px;">
		<div class="newslist">
			<ul class="news_content">
				<li>
					<div class="n_name" data-status="closed">Мы на МАКС-2013</div>
					<div class="n_date">28.08.2013</div>
					<div class="n_preview">Дорогие друзья и коллеги! С 27 августа по 1 сентября мы участвуем в <%= link_to "Международном авиационно-космическом салоне МАКС", "http://www.aviasalon.com/ru/", :target => '_blank' %></div><div class="n_content"><div class="slider_close btn">Свернуть</div></div>
				</li>
			</ul><br>	
		</div>
		<div class="sections" id="sections">
			<ul style="margin-top: -10px;">
				<li id="square-01">
					<a href="/activities/1" class="block-text" style="text-decoration: none; background: url('/assets/antenni.jpg') no-repeat  bottom;"></a>
				</li>
				<li id="square-02">
					<a href="/activities/2" class="block-text" style="text-decoration: none; background: url('/assets/ships2.jpg') no-repeat  bottom;"></a>
				</li>
				<li id="square-03">
					<a href="/activities/3" class="block-text" style="text-decoration: none; background: url('/assets/comp2.jpg') no-repeat  bottom;"></a>
				</li>
			</ul>
			<ul>
				<li id="square-04">
					<a href="/activities/4" class="block-text" style="text-decoration: none; background: url('/assets/electromagnetic.jpg') no-repeat  bottom;"></a>
				</li>
				<li id="square-05">
					<a href="/activities/5" class="block-text" style="text-decoration: none; background: url('/assets/telescopes.jpg') no-repeat  bottom;"></a>
				</li>
				<li id="square-06">
					<a href="/activities/6" class="block-text" style="text-decoration: none; background: url('/assets/microshema.jpg') no-repeat  bottom;"></a>
				</li>
			</ul>			
			<ul>
				<li id="square-07">
					<a href="/activities/7" class="block-text" style="text-decoration: none; background: url('/assets/robots2.jpg') no-repeat  bottom;"></a>
				</li>
				<li id="square-08">
					<a href="/activities/8" class="block-text" style="text-decoration: none; background: url('/assets/mehanika.jpg') no-repeat  bottom;"></a>
				</li>
				<li id="square-09">
					<a href="/activities/9" class="block-text" style="text-decoration: none; background: url('/assets/pelengators.jpg') no-repeat  bottom;"></a>
				</li>
			</ul>
			<div style="float:none; clear: both;"></div>
		</div>
</div>

app/views/static_pages/vacancies.html.erb
<% @title = 'Вакансии' %>

<div class="main_block">
	<script>$(function(){

		$('.slider').on('click', function(){
			$(this).parent('div').parent('li').find('.job_post').attr('data-status', 'opened');
			preview = $(this).parent('div');
			content = $(this).parent('div').next('div');
			preview.slideUp('fast');
			content.slideDown('fast');
		});

		$('.slider_close').on('click', function(){
			$(this).parent('div').parent('li').find('.job_post').attr('data-status', 'closed');
			content = $(this).parent('div');
			preview = $(this).parent('div').prev('div');
			content.slideUp('fast');
			preview.slideDown('fast');
		});

		$('.job_post').on('click', function(e){
			preview = $(this).parent('li').find('.job_preview_2');
			content = $(this).parent('li').find('.job_content_all');
			if ($(this).attr('data-status') === 'opened') {
				$(this).attr('data-status', 'closed');
				preview.slideDown('fast');
				content.slideUp('fast');
			}
			else if ($(this).attr('data-status') === 'closed') {
				$(this).attr('data-status', 'opened');
				preview.slideUp('fast');
				content.slideDown('fast');
			};
		});

	});
	</script>

	<div style="margin-left: 30px; font-size: 20px;">В данный момент открытых вакансий нет. <br> Следите за обновлениями.</div>
	<div style="clear: both;"></div>
</div>